name: CI
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, feature/** ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8
      - name: Lint (flake8)
  continue-on-error: true
  run: flake8 .
      - name: Run tests
        run: python -m pytest -q


